apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app: hello
resources:
- pvc-for-grafana+prometheus.yml
- services-grafana-prometheus.yml
- grafana-deployment.yml
- prometheus-deployment.yml